### PR TITLE
add github-discord issue

### PR DESCRIPTION
**Pull request by chen982**

### CODE REVIEW

**Comment by alabulei1** [comment]
The format of your Rust code seems not correct.  The rust code didn't include a `cargo.toml` file.  Did you compile the rust code successfully? @chen982

**Comment by chen982** [comment]
I used the former structure of this project, which contains all the the rust code in the src folder with a carg.toml file outside

**Comment by alabulei1** [comment]
> I used the former structure of this project, which contains all the the rust code in the src folder with a carg.toml file outside

Now we have restructured the repo. Please follow the new style. Thanks.

**Comment by chen982** [comment]
Ok, I will make a new pr

**Comment by alabulei1** [comment]
Also, I have another question. Could you help me confirm that is the `["name"]` parameter correct to edit the label name in your JS code?

**Comment by chen982** [comment]
yeah, you can use the "x["issue"]["labels"][0]["name"]" to filter the label name

**Comment by alabulei1** [comment]
How about two labels?

**Comment by chen982** [comment]
Use "x["issue"]["labels"][0]["name"]" and "x["issue"]["labels"][1]["name"]"

**Pull request closed without merging**
